# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
    ]
